### ISSUE TITLE
Dataset Categorization

### ISSUE THREAD

**Issue by mval23** [mval23/MDSynergy#2]
https://www.youtube.com/watch?v=Q9zv369Ggfk
- [ ] Libreries
- [ ] Data

**Comment by mval23** [comment]
.

**Comment by mval23** [comment]
- [ ] divide dataset in groups
- [ ] put the prompt
- [ ] tell david

**Comment by leodavid0109** [comment]
Here is a useful page for what is coming...
https://medium.com/@olahsymbo/fine-tuning-openai-gpt-3-to-build-custom-chatbot-fe2dea524561

Basically it talks about how to apply our dataset and fine-tuning it correctly with Da-Vinci algorithm
