### ISSUE TITLE
Artificial Neural Network that writes code

### ISSUE THREAD

**Issue by mval23** [mval23/MDSynergy#4]

**Comment by mval23** [comment]
https://realpython.com/python-ai-neural-network/

**Comment by mval23** [comment]
https://youtube.com/playlist?list=PLUF7uytFiKKUrFMzku0s2YkjqnlkUhCk8&si=ghbHAhpc6ILbR2qe

**Comment by mval23** [comment]
https://www.youtube.com/watch?v=Q9zv369Ggfk

**Comment by leodavid0109** [comment]
https://beebom.com/how-train-ai-chatbot-custom-knowledge-base-chatgpt-api/

**Comment by leodavid0109** [comment]
Some ideas about how to implement the optimization part of the AI Model.
https://dev.to/jmgb27/how-to-use-artificial-intelligence-to-optimize-your-code-tips-for-programmers-3pmm

**Comment by leodavid0109** [comment]
Proposal of courses in Coursera (Idea to do a parallel learnign and doing of the project)
- https://www.coursera.org/learn/neural-networks-deep-learning?#modules
- https://www.coursera.org/projects/tensorflow-for-ai-neural-network-representation#details
- https://www.coursera.org/learn/build-basic-generative-adversarial-networks-gans#modules
- https://www.coursera.org/learn/natural-language-processing-tensorflow
