### ISSUE TITLE
Fine tune Llama

### ISSUE THREAD

**Issue by mval23** [mval23/MDSynergy#6]

**Comment by mval23** [comment]
https://www.youtube.com/watch?v=MDA3LUKNl1E

**Comment by leodavid0109** [comment]
git clone https://github.com/oobabooga/text-generation-webui

**Comment by leodavid0109** [comment]
https://www.youtube.com/watch?v=Ud_86SaCTrM
VIDEO CODE LLAMA

**Comment by mval23** [comment]
Dropped :(
